<?xml version="1.0" encoding="UTF-8"?>
<TestRun id="deb316e4-d829-4920-b8ff-fb6aa4bc52eb" name="Admin@D46 2022-03-17 10:25:11" runUser="D46\Admin" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
  <TestSettings name="Local" id="904e1636-c7f5-45e3-b84f-b9dab1cc98be">
    <Description>These are default test settings for a local test run.</Description>
    <Deployment enabled="false" runDeploymentRoot="Admin_D46 2022-03-17 10_25_11">
      <DeploymentItem filename="D:\KTPM\Calculator\Calculator\Calculator\bin\Debug\Calculator.exe" />
    </Deployment>
    <Execution>
      <TestTypeSpecific />
      <AgentRule name="Execution Agents">
      </AgentRule>
    </Execution>
  </TestSettings>
  <Times creation="2022-03-17T10:25:11.9530000+07:00" queuing="2022-03-17T10:25:11.9870000+07:00" start="2022-03-17T10:25:11.9900000+07:00" finish="2022-03-17T10:25:12.1210000+07:00" />
  <ResultSummary outcome="Failed">
    <Counters total="1" executed="1" error="0" failed="1" timeout="0" aborted="0" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" passed="0" completed="0" inProgress="0" pending="0" />
  </ResultSummary>
  <TestDefinitions>
    <UnitTest name="TestRadix2" storage="d:\ktpm\calculator\calculator\calculatortester\bin\debug\calculatortester.dll" id="4be46d66-e044-9a78-54b3-5691b4b5f764">
      <Execution id="5aca112a-19d0-4250-ab79-99cde7839359" />
      <TestMethod codeBase="D:/KTPM/Calculator/Calculator/CalculatorTester/bin/Debug/CalculatorTester.DLL" adapterTypeName="Microsoft.VisualStudio.TestTools.TestTypes.Unit.UnitTestAdapter, Microsoft.VisualStudio.QualityTools.Tips.UnitTest.Adapter, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" className="CalculatorTester.Cau3_Radix, CalculatorTester, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" name="TestRadix2" />
    </UnitTest>
  </TestDefinitions>
  <TestLists>
    <TestList name="Results Not in a List" id="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestList name="All Loaded Results" id="19431567-8539-422a-85d7-44ee4e166bda" />
  </TestLists>
  <TestEntries>
    <TestEntry testId="4be46d66-e044-9a78-54b3-5691b4b5f764" executionId="5aca112a-19d0-4250-ab79-99cde7839359" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
  </TestEntries>
  <Results>
    <UnitTestResult executionId="5aca112a-19d0-4250-ab79-99cde7839359" testId="4be46d66-e044-9a78-54b3-5691b4b5f764" testName="TestRadix2" computerName="D46" duration="00:00:00.0124830" startTime="2022-03-17T10:25:11.9940000+07:00" endTime="2022-03-17T10:25:12.1100000+07:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Failed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="5aca112a-19d0-4250-ab79-99cde7839359">
      <Output>
        <ErrorInfo>
          <Message>Test method CalculatorTester.Cau3_Radix.TestRadix2 did not throw expected exception System.ArgumentException.</Message>
        </ErrorInfo>
      </Output>
    </UnitTestResult>
  </Results>
</TestRun>