<?xml version="1.0" encoding="UTF-8"?>
<TestRun id="19004e78-73b4-40ca-8d6f-5d860a30be5e" name="Admin@D46 2022-03-17 10:29:59" runUser="D46\Admin" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
  <TestSettings name="Local" id="904e1636-c7f5-45e3-b84f-b9dab1cc98be">
    <Description>These are default test settings for a local test run.</Description>
    <Deployment enabled="false" runDeploymentRoot="Admin_D46 2022-03-17 10_29_59">
      <DeploymentItem filename="D:\KTPM\Calculator\Calculator\Calculator\bin\Debug\Calculator.exe" />
    </Deployment>
    <Execution>
      <TestTypeSpecific />
      <AgentRule name="Execution Agents">
      </AgentRule>
    </Execution>
  </TestSettings>
  <Times creation="2022-03-17T10:29:59.5280000+07:00" queuing="2022-03-17T10:29:59.5450000+07:00" start="2022-03-17T10:29:59.5470000+07:00" finish="2022-03-17T10:29:59.6740000+07:00" />
  <ResultSummary outcome="Failed">
    <Counters total="1" executed="1" error="0" failed="1" timeout="0" aborted="0" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" passed="0" completed="0" inProgress="0" pending="0" />
  </ResultSummary>
  <TestDefinitions>
    <UnitTest name="TestCoverEx2" storage="d:\ktpm\calculator\calculator\calculatortester\bin\debug\calculatortester.dll" id="4f654c82-d258-4bdf-30b0-fbc2a9720940">
      <Execution id="f49a7fb0-3e34-42cf-9e8a-05d4c39ea0b3" />
      <TestMethod codeBase="D:/KTPM/Calculator/Calculator/CalculatorTester/bin/Debug/CalculatorTester.DLL" adapterTypeName="Microsoft.VisualStudio.TestTools.TestTypes.Unit.UnitTestAdapter, Microsoft.VisualStudio.QualityTools.Tips.UnitTest.Adapter, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" className="CalculatorTester.Cau3_Radix, CalculatorTester, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" name="TestCoverEx2" />
    </UnitTest>
  </TestDefinitions>
  <TestLists>
    <TestList name="Results Not in a List" id="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestList name="All Loaded Results" id="19431567-8539-422a-85d7-44ee4e166bda" />
  </TestLists>
  <TestEntries>
    <TestEntry testId="4f654c82-d258-4bdf-30b0-fbc2a9720940" executionId="f49a7fb0-3e34-42cf-9e8a-05d4c39ea0b3" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
  </TestEntries>
  <Results>
    <UnitTestResult executionId="f49a7fb0-3e34-42cf-9e8a-05d4c39ea0b3" testId="4f654c82-d258-4bdf-30b0-fbc2a9720940" testName="TestCoverEx2" computerName="D46" duration="00:00:00.0119725" startTime="2022-03-17T10:29:59.5510000+07:00" endTime="2022-03-17T10:29:59.6640000+07:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Failed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="f49a7fb0-3e34-42cf-9e8a-05d4c39ea0b3">
      <Output>
        <ErrorInfo>
          <Message>Test method CalculatorTester.Cau3_Radix.TestCoverEx2 did not throw expected exception System.ArgumentException.</Message>
        </ErrorInfo>
      </Output>
    </UnitTestResult>
  </Results>
</TestRun>